dist: trusty
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - ninja-build
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
env:
  global:
    - CFLAGS="-Wall -Wextra -pedantic -Wconversion -Wshadow -Wcast-qual -Wmissing-prototypes -march=native"
    - CXXFLAGS="-Wall -Wextra -pedantic -Wconversion -Wshadow -Wcast-qual -march=native"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir -p build
  - cd build
  - cmake .. -G Ninja -DUMIGV_RANGES_BUILD_TESTS=ON -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}
  - ninja -j $(cat /proc/cpuinfo | grep processor | wc -l)
  - ninja test
